### ISSUE TITLE
ESPHome custom climate deprecated

### ISSUE THREAD

**Issue by diybateriaslifepo4** [lNikazzzl/tcl_ac_esphome#8]
![Image](https://github.com/user-attachments/assets/9f2eb172-4a0e-4546-aa78-9a315f0eab92)

Hello, I'm using this component and it works pretty well, but I have a little problem because it disconnects from HA for a few seconds frequently. I've been doing some research to see if I can find a way to update the sensors every longer to see if this way the ESP doesn't get saturated and works better, and I found this message on the ESPHome website.

I don't know if you were aware of it and if you've thought about converting the custom into a component as indicated.
Thanks and best regards.

**Comment by lNikazzzl** [comment]
I'm pretty stable. Uptime is up to a month. No disconnections have been observed. Esp8266. The esphom version is old, but I updated HA a couple of months ago

**Comment by lucize** [comment]
@lNikazzzl I can also say this is stable, but in regards to latest esphome changes, do you have some hints on how to use it without custom component?

**Comment by lucize** [comment]
@diybateriaslifepo4 @lNikazzzl  this is a very crude adaptation using chatgpt and deepseek to convert the code to external components
I'm using the AC as a heat pump so I've removed the code related to swing, I guess is easily added  but I can't test it as my unit is connected to a plate heat exchanger

for sure there can be more things added to climate.py

extract te zip file in a ~/config/component folder

[tcl_climate.zip](https://github.com/user-attachments/files/19077305/tcl_climate.zip)

this is a snipped for the yaml

```
external_components:
  - source: components

#adjust the gpios as needed

uart:
  id: uart_bus
  tx_pin: GPIO18
  rx_pin: GPIO19
  baud_rate: 9600
  parity: EVEN

climate:
  - platform: tcl_climate
    id: my_custom_climate
    name: "HAVC TCL"
```
